import streamlit as st
from prompts import ECGResult, build_prompt
from llm import generate_text

st.set_page_config(page_title="ECG AIGC Explainer", page_icon="❤️", layout="centered")

st.title("ECG → Multi-level Explanation (AIGC Demo)")
st.caption("Upload ECG / select a sample → get Medical / Patient-friendly / One-sentence explanations.")

# ✅ 先用假的模型輸出，之後再換成你的真模型推論結果
def dummy_ecg_inference() -> ECGResult:
    return ECGResult(
        rhythm="Atrial Fibrillation",
        confidence=0.76,
        features=[
            "Irregular RR intervals",
            "Absence of distinct P waves",
            "Beat-to-beat variability in rhythm"
        ],
    )

st.subheader("1) ECG Input")

st.markdown("**Input mode:** Sample ECG (Demo)")

st.info(
    "This demo uses a representative sample ECG to demonstrate the complete AIGC pipeline "
    "from ECG analysis to multi-level explanation generation."
)

st.subheader("2) Model Output (structured)")
result = dummy_ecg_inference()
st.json({
    "rhythm": result.rhythm,
    "confidence": result.confidence,
    "features": result.features
})

st.subheader("3) AIGC: Generate explanations")

audience = st.selectbox("Explanation level", ["medical", "patient", "one_sentence"])
prompt = build_prompt(result, audience)

with st.expander("Show prompt (for report / agent log)"):
    st.code(prompt, language="text")


if st.button("Generate explanation"):
    with st.spinner("Generating explanation with Generative AI..."):
        output = generate_text(prompt)
    st.success("Generation completed")
    st.write(output)
    if audience == "medical":
        st.write("The ECG pattern suggests an irregular rhythm consistent with the predicted class, with key features including irregular RR intervals and absent distinct P waves. Confidence is moderate-high; interpret in clinical context and correlate with symptoms and additional leads.")
    elif audience == "patient":
        st.write("The pattern looks like an irregular heartbeat. This result is generated by an AI model and doesn’t confirm a diagnosis, but it may be worth discussing with a healthcare professional for a more accurate evaluation.")
    else:
        st.write("The heartbeat pattern looks irregular, so it may be helpful to have it checked by a professional.")
